CREATE TABLE users(
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(100) NOT NULL,
password VARCHAR(255) NOT NULL,
role VARCHAR(20) NOT NULL DEFAULT 'USERKA',
status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
)


INSERT INTO users(email, first_name, last_name, password, role, status) VALUES ('adminka@gmail.com', 'Adminka', 'Lavlays', '$2a$12$zsM7tNIswA27pWBbHPDd8e1aNWIn89aSw9bHHZeEE4a1Yj.DzToo2', 'ADMIN', 'ACTIVE')
INSERT INTO users(email, first_name, last_name, password, role, status) VALUES ('userka@gmail.com', 'Userka', 'Use', '$2a$12$U9RoqHfWBlArSFHp54sl3.5AnDBBoTK0.yNQYBRsLSC2CpDk5INz.', 'USER', 'ACTIVE')